app/views/dashboard_views.py
from flask import render_template, request, flash, redirect, url_for, logging, session
from wtforms import BooleanField, Form, IntegerField, PasswordField, StringField, TextAreaField, validators, widgets
from wtforms.fields.html5 import DateField, DateTimeLocalField
import datetime
from wtforms.validators import DataRequired, InputRequired, Required
from passlib.hash import sha256_crypt
from functools import wraps


import os
import re
from wtforms.fields.core import SelectField, SelectMultipleField
from app import mysql

from flask.blueprints import Blueprint
from flask import current_app
from flask.json import jsonify
from flask.helpers import make_response
import bleach

# import the function if an user logged in
from app.views.admin_views import is_logged_in

dashboard_views = Blueprint('dashboard_views', __name__, static_folder="static",
                            template_folder="templates")


# Check User Acces Level
def access_level():

    cur = mysql.connection.cursor()

    # Execute
    result = cur.execute(
        "SELECT  * FROM access_premission WHERE user_id=%s", [session["id"]])

    user = cur.fetchall()

    # close connection
    cur.close()

    return user[0]["access_level"]


# Dashboard
@dashboard_views.route("/dashboard", methods=["GET", "POST"])
@is_logged_in
def dashboard():

    # Create Cursor
    cur = mysql.connection.cursor()

    # Get user's Dashboard
    result = cur.execute(
        "SELECT * FROM Veranstaltung  INNER JOIN dashboard ON dashboard.veranSt_id = Veranstaltung.ID WHERE dashboard.user_id =%s ORDER BY Veranstaltung.Titel", [session["id"]])

    veranstaltungen = cur.fetchall()

    # Close Connection
    cur.close()

    return render_template("dashboard/dashboard.html", veranSt=veranstaltungen, access_level=access_level())


# Veranstaltungen Form Class
class VeranStForm(Form):
    Stil = IntegerField("Stil", [validators.NumberRange(min=0)])
    Verantwortlich = StringField(
        "Verantwortlich", [validators.length(min=1, max=255)])
    Mitarbeiter = StringField(
        "Mitarbeiter", [validators.length(min=1, max=255)])
    Titel = StringField(
        "Titel", [validators.length(min=1, max=255)])
    Kopftext = TextAreaField(
        "Kopftext", [validators.Length(min=1, max=255)])
    Fusstext = TextAreaField(
        "Fusstext", [validators.Length(min=1, max=255)])
    Kurztext = TextAreaField(
        "Kurztext", [validators.Length(min=1, max=20)])


# Add Verranstaltung
@ dashboard_views.route("/add_veranSt", methods=["GET", "POST"])
@ is_logged_in
def add_veranstaltung():
    if access_level() == "full_access":
        form = VeranStForm(request.form)
        if request.method == "POST" and form.validate():
            Stil = form.Stil.data
            Verantwortlich = form.Verantwortlich.data
            Mitarbeiter = form.Mitarbeiter.data
            Titel = form.Titel.data
            Kopftext = form.Kopftext.data
            Fusstext = form.Fusstext.data
            Kurztext = form.Kurztext.data

            # Create Curser
            cur = mysql.connection.cursor()

            # Execute
            cur.execute("INSERT INTO Veranstaltung( Stil, Verantwortlich,Mitarbeiter, Titel, Kopftext,Fusstext,Kurztext ) VALUES(%s, %s, %s,%s, %s,%s, %s)",
                        (Stil,  Verantwortlich, Mitarbeiter, Titel, Kopftext, Fusstext, Kurztext))
            # Get the created Veranstaltung's id
            veranSt_id = cur.lastrowid

            # Add the user id and veranSt_id into dashboard table
            cur.execute("INSERT INTO dashboard(user_id, veranSt_id, is_owner) VALUES(%s,%s, %s)",
                        (session["id"], veranSt_id, 1))

            # Commit to DB
            mysql.connection.commit()

            # Close connection
            cur.close()

            flash("Veranstaltung Created", "success")

            return redirect(url_for("dashboard_views.dashboard"))

        return render_template("dashboard/add_veranSt.html", form=form)
    else:
        return redirect(url_for("dashboard_views.dashboard"))


# Get Veranstaltung's users
@dashboard_views.route("dashboard/veranstaltungs/users/<int:id>", methods=["GET", "POST"])
@is_logged_in
def veranstalung_users(id):
    if access_level() != "no_access":
        # Create curser
        cur = mysql.connection.cursor()

        # Check if user is own of the lecture
        result = cur.execute("SELECT * FROM dashboard  WHERE user_id=%s AND veranSt_id=%s", [
            session["id"], id])

        user = cur.fetchone()

        if result > 0:
            # Execute
            cur.execute(
                "SELECT users.first_name, users.last_name,users.email, users.dept, dashboard.user_id, dashboard.veranSt_id FROM users RIGHT JOIN dashboard ON users.id = dashboard.user_id WHERE veranSt_id =%s ", [id])
            veranSt_users = cur.fetchall()
            # Close cursor
            cur.close()

            return render_template('dashboard/veranSt_users.html', veranSt_users=veranSt_users, veranSt_id=id, access_level=access_level())
        else:
            # Close connection
            cur.close()
            flash("Unauthorized, Please login", "danger")
            return redirect(url_for("dashboard_views.dashboard"))
    return redirect(url_for("dashboard_views.dashboard"))


# Get the users for selecting them and assinging them to a lecture
@dashboard_views.route("/dashboard/veranstaltungs/users/all", methods=["GET"])
@is_logged_in
def all_users():
    # create curser
    cur = mysql.connection.cursor()

    # Execute
    result = cur.execute("SELECT * FROM users")

    users = cur.fetchall()

    # close connection
    cur.close()

    if result > 0:
        res = make_response(jsonify(users), 200)
        return res


# Assign a user to an Veranstaltung
@dashboard_views.route("/dashboard/veranstaltungs/users/assign", methods=["POST"])
@is_logged_in
def assign_users():
    req = request.get_json()
    if access_level() == "full_access":
        if request.method == "POST":

            user_id = req["user_id"]
            veranSt_id = req["veranSt_id"]

            # Create Curser
            cur = mysql.connection.cursor()

            # Check if user owner is
            cur.execute("SELECT is_owner FROM dashboard WHERE user_id=%s AND veranSt_id=%s", [
                        session["id"], veranSt_id])

            user = cur.fetchone()

            if user["is_owner"] == 1:
                cur.execute(
                    "INSERT INTO dashboard(user_id, veranSt_id) VALUES(%s,%s)", (user_id, veranSt_id))

                # Commit to DB
                mysql.connection.commit()

                flash("User Added ", "success")
            else:
                flash(
                    "Permission Denied, You are not the owner of this lecture", "danger")

            # Close connection
            cur.close()

            res = make_response(jsonify("Ok", 200))
            return res
    else:
        res = make_response(jsonify("Not Fund", 404))
        return res


# Delete a user from a lecture
@dashboard_views.route("dashboard/veranstaltungs/users/delete/<int:user_id>/<int:veranSt_id>", methods=["POST"])
@is_logged_in
def delete_veranSt_user(user_id, veranSt_id):

    # Create Curser
    cur = mysql.connection.cursor()

    # Check if user owner is
    cur.execute("SELECT * FROM dashboard WHERE user_id=%s AND veranSt_id=%s", [
                session["id"], veranSt_id])

    user = cur.fetchone()

    if user["user_id"] == user_id:
        flash("Permission Denied, You can not delete yourself, please go to your dashboard and delete the lecture", "danger")
        return redirect(url_for("dashboard_views.veranstalung_users", id=veranSt_id))
        # close connection
        cur.close()

    elif user["is_owner"] == 1:
        # Execute
        cur.execute("DELETE FROM dashboard WHERE user_id=%s AND veranSt_id=%s", [
                    user_id, veranSt_id])

        # Commit to DB
        mysql.connection.commit()

        # Close Connection
        cur.close

        flash("User Deleted", "success")

        return redirect(url_for("dashboard_views.veranstalung_users", id=veranSt_id))

    else:
        # close connection
        cur.close()
        flash("Permission Denied, You are not the owner of this lecture", "danger")
        return redirect(url_for("dashboard_views.veranstalung_users", id=veranSt_id))


# Edit Veranstaltung
@ dashboard_views.route('/edit_veranSt/<string:ID>', methods=['GET', 'POST'])
@ is_logged_in
def edit_veranSt(ID):
    if access_level() == "full_access":
        # Create cursor
        cur = mysql.connection.cursor()

        result = cur.execute("SELECT * FROM dashboard  WHERE user_id=%s AND veranSt_id=%s", [
            session["id"], ID])

        user = cur.fetchone()

        if result > 0:

            # Get Veranstaltung by id
            result = cur.execute(
                "SELECT * FROM Veranstaltung WHERE ID = %s", [ID])

            veranSt = cur.fetchone()

            # Close the connection
            cur.close()

            # Get form
            form = VeranStForm(request.form)

            # Populate Veranstaltung form fields
            form.Stil.data = veranSt['Stil']
            form.Verantwortlich.data = veranSt['Verantwortlich']
            form.Mitarbeiter.data = veranSt['Mitarbeiter']
            form.Titel.data = veranSt['Titel']
            form.Kopftext.data = veranSt['Kopftext']
            form.Fusstext.data = veranSt['Fusstext']
            form.Kurztext.data = veranSt['Kurztext']

            if request.method == 'POST' and form.validate():
                Stil = request.form['Stil']
                Verantwortlich = request.form['Verantwortlich']
                Mitarbeiter = request.form['Mitarbeiter']
                Titel = request.form['Titel']
                Kopftext = request.form['Kopftext']
                Fusstext = request.form['Fusstext']
                Kurztext = request.form['Kurztext']

app/templates/dashboard/add_aufgabe.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- this will set the page title-->
{% block title %}Add Aufgabe{% endblock %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text"></div>
    <div class="showcase-table card">
      <h1>Add Aufgabe</h1>
      {% from "/includes/_formhelpers.html" import render_field %}
      <form method="POST" action="">
        <div class="form-group">
          {{ render_field(form.Name, class_="form-control")}}
        </div>
        <div class="form-group">
          {{ render_field(form.Titel, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Gebiet, class_="form-control")}}
        </div>
        <div class="form-group">
          {{ render_field(form.version, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Aufgabe, class_="form-control", class="editor") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Loesung, class_="form-control", class="editor") }}
        </div>

        <p>
          <input class="btn btn-primary" type="submit" value="Submit" />
        </p>
      </form>
    </div>
  </div>
</section>


{% endblock %}

app/templates/dashboard/add_blatt.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- this will set the page title-->
{% block title %}Add Blatt{% endblock %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text"></div>
    <div class="showcase-table card">
      <h1>New Blatt</h1>
      <form action="" method="POST" id="aufgaben_form">
        
        <div id="veranstaltung" data-veranstaltung="{{ veranSt}} "></div>

        <div class="form-row">
          <div class="col-md-2 mb-4">
            <label for="numberOfBlatt">Nr</label>
            <input
              required
              id="Nr"
              class="form-control"
              type="number"
              name="Nr"
              value="{{request.form.Nr}}"
              placeholder="Nr"
            />
          </div>
          <div class="col-md-5 mb-4">
            <label for="nameOfBlatt">Name</label>
            <input
              required
              id="Name"
              class="form-control"
              type="text"
              name="Name"
              placeholder="Name"
            />
          </div>
          <div class="col-md-5 mb-4">
            <label for="titleOfBlatt">Titel</label>
            <input
              required
              id="Titel"
              class="form-control"
              type="text"
              name="Titel"
              placeholder="Titel"
            />
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-4 mb-4">
            <label for="ausgabeOfBlatt">Ausgabe</label>
            <input
              required
              id="Ausgabe"
              class="form-control"
              type="date"
              name="Ausgabe"
            />
          </div>
          <div class="col-md-4 mb-4">
            <label for="AbgabeOfBlatt">Abgabe</label>
            <input
              required
              id="Abgabe"
              class="form-control"
              type="date"
              name="Abgabe"
            />
          </div>
          <div class="col-md-4 mb-4">
            <label for="StilOfBlatt">Stil</label>
            <input
              required
              id="Stil"
              class="form-control"
              type="number"
              name="Stil"
              placeholder="Stil"
            />
          </div>
        </div>

        <div class="form-row">
          <div class="col-md-6 mb-4">
            <label for="ZusatzOfBlatt">Zusatz</label>
            <input
              required
              id="Zusatz"
              class="form-control"
              type="text"
              name="Zusatz"
              placeholder="Zusatz"
              required
            />
          </div>
          <div class="col-md-6 mb-4">
            <label for="aufgabenOfBlatt">Aufgaben</label>
            <select
              name="aufgaben"
              id="select_aufgaben"
              class="form-control"
              data-live-search="true"
            >
              <option disabled hidden selected>Select Aufgaben ...</option>
            </select>
          </div>
        </div>

        <!-- prettier-ignore -->
        <button
        type="submit"
        id="submit_blatt"
        class="btn btn-primary btn-block mt-5 mb-4">Submit</button>

        <div class="form-row">
          <div class="col-md-12 mt-6 table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Aufgabe</th>
                  <th>Punkte</th>
                  <th></th>
                </tr>
              </thead>
              <tbody id="aufgaben_list"></tbody>
            </table>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>

<!-- import the javascript file-->
<script src="{{ url_for('static', filename='dist/addBlatt.js') }}"></script>

{% endblock %}

app/templates/dashboard/add_veranSt.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- this will set the page title-->
{% block title %}Add Veranstaltung{% endblock %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text"></div>
    <div class="showcase-table card">
      <h1>Add Veranstaltung</h1>
      {% from "/includes/_formhelpers.html" import render_field %}
      <form method="POST" action="">
        <div class="form-group">
          {{ render_field(form.Stil, class_="form-control")}}
        </div>
        <div class="form-group">
          {{ render_field(form.Verantwortlich, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Mitarbeiter, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Titel, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Kopftext, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Fusstext, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Kurztext, class_="form-control") }}
        </div>
        <p><input class="btn btn-primary" type="submit" value="Submit" | safe /></p>
      </form>
    </div>
  </div>
</section>


{% endblock %}

app/templates/dashboard/aufgabe.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- this will set the page title-->
{% block title %}Aufgabe{% endblock %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
    <div class="container grid-1">
        <div class="showcase-text"></div>
        <div class="showcase-table card">
            <div>
                <h1>Aufgabe: {{aufgabe.Titel}}</h1>
                {{aufgabe.Aufgabe | safe}}
            </div>
            <hr>
            <div>
                <h1>Loesung:</h1>
                {{aufgabe.Loesung | safe}}
            </div>
        </div>
    </div>
</section>

{% endblock %}

app/templates/dashboard/aufgaben_dashboard.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1" >
    <div class="showcase-text">
      <h1>Welcome<small> {{session.first_name}}</small> to Aufgaben und Loesungen</h1>
      {% if access_level == "full_access" %}
       <a href="/add_aufgabe" class="btn btn-success btn-outline">Add New Aufgabe</a>
       {% endif %}
    </div>
    <div class="showcase-table card table-responsive">
      {% if access_level == "full_access" %}
      <h3>You can add a new Aufgabe, edit, or also delete it</h3>
      
      <table class="table table-striped">
        <tr>
          <th>Name</th>
          <th>Title</th>
          <th>Gebiet</th>
          <th>Date</th>
          <th>version</th>
          <th>Rechte</th>
          <th></th>
          <th></th>
        </tr>

        {% for aufgabe in aufgaben%}
        <tr>
          <td>{{aufgabe.Name}}</td>
          <td>{{aufgabe.Titel}}</td>
          <td>{{aufgabe.Gebiet}}</td>
          <td>{{aufgabe.ts}}</td>
          <td>{{aufgabe.version}}</td>
          <td>{{aufgabe.Rechte}}</td>
          <td>
            <a href="edit_aufgabe/{{aufgabe.ID}}" class="btn btn-default pull-right"
              >Edit</a
            >
          </td>
          <td>
            <form
              action="{{url_for('dashboard_views.delete_aufgabe', ID=aufgabe.ID)}}"
              method="POST"
            >
              <input type="hidden" name="_method" value="DELETE" />
              <input type="submit" value="Delete" class="btn btn-danger" />
            </form>
          </td>
        </tr>
        {%endfor%}
      </table>
        {%  elif access_level == "read_access" %}
          <h3>You can just read hier  Aufgaben and Loesungen </h3>
          <ul class="list-group">
            {% for aufgabe in aufgaben %}
            <li class="list-group-item ">
              <a href="aufgabe/{{aufgabe.ID}}" class="stretched-link">{{aufgabe.Titel}}</a>
            </li>
            {% endfor %}
          </ul>
        {%  else %}
          <h3> Unfortunately, you have no access to Aufgaben or Loesungen, Please connect to the Admin</h3>
      </div>
      {% endif %}
  </div>
</section>
{% endblock %}

app/templates/dashboard/blatt.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text">
      <h1>Dear {{session.first_name}}</h1>
      {% if access_level == "full_access" %}
        <h3>You can here add  a new Blatt, edit, or also delete it  </h3>
        <a href="/dashboard/veranstaltungs/blatt/add/{{blatt[0].Veranstaltung}}" class="btn btn-success btn-outline">Add New Blatt</a>
        {%  elif access_level == "read_access" %}
        <h3>You have only read access </h3>
        {%  else %}
          <h3> Unfortunately, you have no access to anything, Please connect to the Admin</h3>
      {% endif %}
    </div>
    <div class="showcase-table card table-responsive">  
      {% if access_level != "no_access" %}    
      <table class="table table-striped">
        <tr>
          <th>Nr</th>
          <th>Name</th>
          <th>Titel</th>
          <th>Ausgabe</th>
          <th>Abgabe</th>
          <th>Zusatz</th>
          <th>Stil</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        {% for b in blatt%}
        <tr>
          <td>{{b.Nr}}</td>
          <td>{{b.Name}}</td>
          <td>{{b.Titel}}</td>
          <td>{{b.Ausgabe}}</td>
          <td>{{b.Abgabe}}</td>
          <td>{{b.Zusatz}}</td>
          <td>{{b.stil}}</td>
          <td><a href="/dashboard/veranstaltungs/blatt/print/{{ b.Veranstaltung}}/{{b.ID}}/1" class="btn btn-info pull-right btn-sm"
            >Print With Loesung</a></td>
          <td>
            <a href="/dashboard/veranstaltungs/blatt/print/{{ b.Veranstaltung}}/{{b.ID}}/0" class="btn btn-info pull-right btn-sm"
              >Print Just Aufgabe</a
            >
          </td>
          {% if access_level == "full_access" %}
            <td>
              <a href="/dashboard/veranstaltungs/blatt/edit/{{ b.Veranstaltung}}/{{b.ID}}" class="btn btn-primary pull-right">Edit</a>
            </td>
          {% endif %}
          <td>
            <form action="{{url_for('dashboard_views.delete_blatt', ID=b.ID, veranSt=b.Veranstaltung)}}" method="POST">
              <input type="hidden" name="_method" value="DELETE" />
              <input type="submit" value="Delete" class="btn btn-danger" />
            </form>
          </td>
        </tr>
        {%endfor%}
      </table>
    </div>
    {% endif %}
  </div>
</section>
{%endblock%}

app/templates/dashboard/dashboard.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text">
      <h1>{{session.first_name}}'s Dashboard</h1>
      {% if access_level == "full_access" %}
      <h3>You have have full access</h3>
      {{msg}}
      <a href="/add_veranSt" class="btn btn-success btn-outline">Add New Veranstaltung</a>
      {%  elif access_level == "read_access" %}
          <h3>You have only read access </h3>
          {%  else %}
          <h3> Unfortunately, you have no access to anything, Please connect to the Admin</h3>
      {% endif %}
    </div>
    <div class="showcase-table card table-responsive">
      {% if access_level != "no_access" %}
      <table class="table table-striped">
        <tr>
          <th>Verantwortlich</th>
          <th>Mitarbeiter</th>
          <th>Titel</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          
        </tr>
        {% for v in veranSt %}
        <tr>
          <td>{{v.Verantwortlich}}</td>
          <td>{{v.Mitarbeiter}}</td>
          <td>{{v.Titel}}</td>
          <td>
            <a href="dashboard/veranstaltungs/users/{{v.ID}}" class="btn btn-info pull-right"
              >Users</a
            >
          </td>
          <td>
            <a href="dashboard/veranstaltungs/blatt/{{v.ID}}" class="btn btn-secondary pull-right"
              >Blatt</a
            >
          </td>
          {% if access_level == "full_access" %}
            <td>
              <a href="edit_veranSt/{{v.ID}}" class="btn btn-primary pull-right"
                >Edit</a
              >
            </td>
          {% endif %}
          <td>
            <form action="{{url_for('dashboard_views.delete_veranSt', ID=v.ID)}}" method="POST">
              <input type="hidden" name="_method" value="DELETE" />
              <input type="submit" value="Delete" class="btn btn-danger" />
            </form>
          </td>
        </tr>
        {%endfor%}
      </table>      
    </div>
    {% endif %}
  </div>
</section>


<hr>
{%endblock%}

app/templates/dashboard/edit_aufgabe.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- this will set the page title-->
{% block title %}Edit Aufgabe{% endblock %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text"></div>
    <div class="showcase-table card">
      <h1>Edit Aufgabe</h1>
      {% from "/includes/_formhelpers.html" import render_field %}
      <form method="POST" action="">
        <div class="form-group">
          {{ render_field(form.Name, class_="form-control") |safe }}
        </div>
        <div class="form-group">
          {{ render_field(form.Titel, class_="form-control") |safe }}
        </div>
        <div class="form-group">
          {{ render_field(form.Gebiet, class_="form-control") |safe }}
        </div>
        <div class="form-goup">
          {{ render_field(form.version, class_="form-control") |safe}}
        </div>
        <div class="form-group">
          {{ render_field(form.Aufgabe, class_="form-control", class="editor") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Loesung, class_="form-control", class="editor") }}
        </div>

        <p><input class="btn btn-primary" type="submit" value="Submit" /></p>
      </form>

    </div>
  </div>
</section>
{% endblock %}

app/templates/dashboard/edit_blatts_aufgaben.html
<!-- to import the base template-->
{% extends "/layout.html" %}

<!-- the page title -->
{% block title %}Edit Blatt's Aufgaben{% endblock %}

<!-- prettier-ignore -->
{% block body %}
<div class="container">
  <h1>Edit Blatt's Aufgaben</h1>
  <form action="" id="edit-aufgaben-form">
    <div id="edit-aufgaben">
      <select
        id="select-aufgaben-edit"
        class="form-control selectpicker"
        data-live-search="true"
      >
        <option disabled hidden selected>Select Aufgaben ...</option>
      </select>
    </div>
    <div id="blatt_id_edit" data-blatt_id="{{ blattId }} "></div>
    <p>
      <input
        type="submit"
        id="submit-editd-aufgaben"
        class="btn btn-primary btn-block mt-5"
        value="Submit"
        |
        safe
      />
    </p>
  </form>
  <table class="table">
    <thead>
      <tr>
        <th>Aufgabe</th>
        <th>Punkte</th>
        <th></th>
      </tr>
    </thead>
    <tbody id="aufgaben-list-edit"></tbody>
  </table>
  {{res}}
</div>
{% endblock %}

app/templates/dashboard/edit_veranSt.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- this will set the page title-->
{% block title %}Edit Vernastaltung{% endblock %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text"></div>
    <div class="showcase-table card">
      <h1>Edit Vernastaltung</h1>
      {% from "/includes/_formhelpers.html" import render_field %}
      <form method="POST" action="">
        <div class="form-group">
          {{ render_field(form.Stil, class_="form-control")}}
        </div>
        <div class="form-group">
          {{ render_field(form.Verantwortlich, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Mitarbeiter, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Titel, class_="form-control") }}
        </div>
        <div class="form-group">
          {{ render_field(form.Kopftext, class_="form-control" ) }}
        </div>
        <div class="form-group">
          {{ render_field(form.Fusstext, class_="form-control" ) }}
        </div>
        <div class="form-group">
          {{ render_field(form.Kurztext, class_="form-control" ) }}
        </div>
        <p><input class="btn btn-primary" type="submit" value="Submit" /></p>
      </form>
    </div>
  </div>
</section>
{% endblock %}

app/templates/dashboard/veranSt_users.html
<!-- to import a base template -->
{% extends "/layout.html" %}

<!-- prettier-ignore -->
{% block body %}
<section class="showcase">
  <div class="container grid-1">
    <div class="showcase-text">
      <h1>Dear {{session.first_name}}</h1>
      {% if access_level == "full_access" %}
      <h3>You can here add  a new User or remove  </h3>
       {%  elif access_level == "read_access" %}
          <h3>You have only read access </h3>
          {%  else %}
          <h3> Unfortunately, you have no access to anything, Please connect to the Admin</h3>
      {% endif %}
    </div>
    <div class="showcase-table card ">

        <div id="veranstaltung" data-veranstaltung="{{ veranSt_id}} "></div>
        
        <div class="col-md-12 mb-4">            
            <select
              required
              aria-required="true"
              name="user"
              id="select_user"
              class="form-control"
              data-live-search="true"
            >
              <option disabled hidden selected value=""
                >Assign To A User</option
              >
            </select>
          </div>
          <div class="flex">
            {% for user in veranSt_users%}
              <div class="card card-users ">
                <!-- <img class="card-img-top" ssrc="{{ url_for('static', filename='img/prof.jpeg') }}" alt="Card image"> -->
                <div class="card-body">
                  <h5 class="card-title">Name: {{user.first_name}} {{user.last_name}}</h5>
                  <p class="card-text">Department: {{user.dept}}</p>
                  <a  href="mailto:{{user.email}}">Email</a> 
                  <br>
                  <form action="{{url_for('dashboard_views.delete_veranSt_user', user_id=user.user_id, veranSt_id=user.veranSt_id)}}" method="POST">
                    <input type="hidden" name="_method" value="DELETE"/>
                    <input type="submit" value="Delete" class="btn btn-outline btn-danger mt-4">
                  </form>
                </div>
              </div>
            {%endfor%}
        </div>
      </div>
  </div>
</section>

  <!-- import the javascript file-->
  <script src="{{ url_for('static', filename='dist/veranStUsers.js') }}"></script>
{%endblock%}